const moviesData = [
    {
        id: "ET00375421", 
        title: "Good Bad Ugly",
        posterUrl: "https://i.postimg.cc/k4B2c3C4/good-bad.jpg", 
        likes: null,
        rating: "8.3/10", 
        votes: "2.9K Votes",
        ageRating: "UA16+",
        languages: ["Tamil", "Telugu", "Hindi", "Malayalam"],
        genres: ["Action", "Crime", "Drama", "Thriller"],
        formats: ["2D", "IMAX 2D"],
        duration: "2h 45m",
        releaseDate: "5 Jun, 2025",
        synopsis: "After spending 17 years in prison to secure a peaceful life for his family, AK emerges to find his son falsely accused of heinous crimes. To clear his son`s name, he must return to the ruthless world he once left behind, confronting dangerous enemies and the haunting shadows of his past.",
        cast: [
            { name: "Ajith Kumar", role: "Actor", imageUrl: "https://i.postimg.cc/6qpt09w4/ajith-kumar.jpg" },
            { name: "Trisha Krishnan", role: "Actor", imageUrl: "https://i.postimg.cc/bv4mgLhx/trisha.jpg" },
            { name: "Arjun Das", role: "Actor", imageUrl: "https://i.postimg.cc/3wLkQbRG/ArjunDas.png" },
            { name: "Priya", role: "Actor", imageUrl: "https://i.postimg.cc/ryGCvqTR/priya.jpg" },
            { name: "Sunil", role: "Actor", imageUrl: "https://i.postimg.cc/mgTb8NwF/sunil.jpg" }
        ],
        trailers: 4 
    },
    {
        id: "ET00383498", 
        title: "Thunderbolts*",
        posterUrl: "https://i.postimg.cc/TPp9L3w2/thunderboltsposter.jpg", 
        likes: null,
        rating: "9.3/10",
        votes: "1.9K Votes",
        ageRating: "UA13+",
        languages: ["English", "Hindi", "Tamil", "Telugu"],
        genres: ["Action", "Superhero"],
        formats: ["2D", "MX4D", "4DX"],
        duration: "1h 35m",
        releaseDate: "30 May, 2025",
        synopsis: "Thunderbolts* are the *New Avengers who mix grit with wit as they bring a new hope to the world.",
        cast: [
            { name: "Florence Pugh", role: "Actor", imageUrl: "https://i.postimg.cc/yNpRBcC6/florence-pugh.webp" },
            { name: "Lewis Pullman", role: "Actor", imageUrl: "https://i.postimg.cc/vTsZdZTH/lewis-pullman.jpg" },
            { name: "Sebastain Stan", role: "Actor", imageUrl: "https://i.postimg.cc/TY2TjSWS/sebastain-stan.webp" },
            { name: "David Harbour", role: "Actor", imageUrl: "https://i.postimg.cc/9Ffjw76H/david-harbour.webp" },
            { name: "Hannah John", role: "Actor", imageUrl: "https://i.postimg.cc/9QG1WxLm/hannah-john-kamen.webp" },
            { name: "Julia Louisa Dreyfuss", role: "Actor", imageUrl: "https://i.postimg.cc/d0sfgPJP/Julia-Louise-Dreyfuss.webp" }
        ],
        trailers: 6
    },
    {
        id: "ET00313498",
        title: "Veera Dheera Sooran Part-2",
        posterUrl: "https://i.postimg.cc/gk484ft6/Veera-Dheera-Sooran-Part-2.jpg", 
        likes: null,
        rating: "8.5/10",
        votes: "9.7K Votes",
        ageRating: "U",
        languages: ["Tamil"],
        genres: ["Action", "Thriller"],
        formats: ["2D"],
        duration: "2h 32m",
        releaseDate: "16 May, 2025",
        synopsis: "On a fateful night, Kaali`s peaceful life is disrupted by SP`s thirst for revenge. When Kaali fights to survive- does he emerge victorious or does his world change forever?",
        cast: [
            { name: "Vikram", role: "Actor", imageUrl: "https://i.postimg.cc/90D5K3tF/vikram.jpg" },
            { name: "S.J. Surya", role: "Actor", imageUrl: "https://i.postimg.cc/sfLRSXsB/sjsurya.jpg" },
            { name: "Suraj", role: "Actor", imageUrl: "https://i.postimg.cc/Vkqy3WMM/suraj-venjaramoodu.avif" },
            { name: "Dushara", role: "Actor", imageUrl: "https://i.postimg.cc/76Qjgs8v/dushara.jpg" }
        ],
        trailers: 1
    },
    {
        id: "ET00390000", 
        title: "Sachein",
        posterUrl: "https://i.postimg.cc/ZR706S5T/sachein.avif", 
        likes: null,
        rating: "8.5/10",
        votes:"9.7K Votes" ,
        ageRating: "UA",
        languages: ["Tamil"],
        genres: ["Drama", "Romantic"],
        formats: ["2D"],
        duration: "2h 30m",
        releaseDate: "3h 0m",
        synopsis: "A happy-go-lucky college student falls in love with a beautiful young woman at first sight, but decides to use a unique approach to get close to her, as she has many admirers in the college. How will their relationship evolve?",
        cast: [
            { name: "Vijay", role: "Actor", imageUrl: "https://i.postimg.cc/wjQWHfBX/vijay.jpg" },
            { name: "Genelia", role: "Actor", imageUrl: "https://i.postimg.cc/gcLNrkJk/genelia.jpg" },
             { name: "Vadivelu", role: "Actor", imageUrl: "https://i.postimg.cc/rm1sYrjw/vadivelu.jpg" },
            { name: "Santhanam", role: "Actor", imageUrl: "https://i.postimg.cc/d1kpq2pJ/Santhanam.jpg" }
        ],
        trailers: 0
    },
    {
           id: "ET00352941",
        title: "Alappuzha Gymkhana",
        posterUrl: "https://i.postimg.cc/x8jmv5Q2/Alappuzha-Gymkhana.webp",
        likes: null,
        rating: "8.4/10",
        votes: "8.8 Votes",
        ageRating: "UA7+",
        languages: [ "Tamil", "Malayalam"],
        genres: ["Comedy", "Drama", "Sports"],
        formats: ["2D", "3D", "IMAX 3D"],
        duration: "3h 0m",
        releaseDate: "27 Jun, 2025",
        synopsis: "A 19-year-old battling an identity crisis and tangled love triangles stumbles into the state boxing championship for grace marks. Under Joshuas tough training, Jojo and his misfit classmates transform from rookies to real contenders. As the tournament nears, they face fierce rivals and their own insecurities in this heartwarming sports comedy of laughter, bruises, and self-discovery.",
        cast: [
            { name: "Naslen", role: "Actor", imageUrl: "https://i.postimg.cc/GtMXG9ZX/Naslen.png" },
            { name: "Lukman Avaran", role: "Actor", imageUrl: "https://i.postimg.cc/tg02hKMG/Lukman-Avaran.jpg" },
            { name: "Baby Jean", role: "Actor", imageUrl: "https://i.postimg.cc/2y5wkrVh/baby-jean.jpg" },
            { name: "Anagha Maya", role: "Actor", imageUrl: "https://i.postimg.cc/FRCSxcHk/hin.jpg" },
            { name: "Anupama", role: "Actor", imageUrl: "https://i.postimg.cc/2yPBsDvz/nanda.jpg" }
        ],
        trailers: 2
    },
    {
        id: "ET00323894",
        title: "Maranamass",
        posterUrl: "https://i.postimg.cc/JnjnskBW/maranamass.jpg",
        likes: null,
        rating: "8.4/10",
        votes: "8.8 Votes",
        ageRating: "UA16+",
        languages: [ "Tamil", "Malayalam"],
        genres: ["Action", "Comedy"],
        formats: ["2D", "IMAX 2D"],
        duration: "3h 10m",
        releaseDate: "06 Dec, 2025",
        synopsis: "Maranamass is a Malayalam starring Basil Joseph, Rajesh Madhavan, Siju Sunny and Suresh Krishna in prominent roles. It is directed by Sivaprasad KV.",
        cast: [
            { name: "Basil Joseph", role: "Actor", imageUrl: "https://i.postimg.cc/J7cNgyYg/basil-joseph.jpg" },
            { name: "Rajesh Madhavan", role: "Actor", imageUrl: "https://i.postimg.cc/bNVtc1x6/rajesh-madhavan.jpg" },
            { name: "Siju Sunny", role: "Actor", imageUrl: "https://i.postimg.cc/kMfVKWpn/Siju-Sunny.avif" },
            { name: "Babu Antony", role: "Actor", imageUrl: "https://i.postimg.cc/ZqxYZSkT/babu-antony.jpg" },
            { name: "Anishma", role: "Actor", imageUrl: "https://i.postimg.cc/c4tsCYqk/anishma.jpg" }
        ],
        trailers: 1
    },
    {
        id: "ET00379758",
        title: "Dargon",
        posterUrl: "https://i.postimg.cc/ZYrjrYkb/dargon.jpg",
        likes: null,
        rating: "8.8/10",
        votes: "41.6K Votes",
        ageRating: "UA16+",
        languages: ["Tamil", "Malayalam"],
        genres: [ "Comedy", "Drama"],
        formats: ["2D", "3D", "IMAX 2D", "4DX"],
        duration: "1h 36m",
        releaseDate: "14 Jun, 2025",
        synopsis: "Ragavan, infamous for his reckless ways and academic struggles, turns to fraud after a heartbreaking breakup, chasing wealth and power. However, his deceit leads him into perilous territory. Can he find a way out, or will his choices seal his fate?",
        cast: [
            { name: "Pradeep Ranganathanr", role: "Voice Actor (Joy)", imageUrl: "https://i.postimg.cc/NGSbXNjc/pradeep-ranganathan.jpg" },
            { name: "Anupama Parameswaran", role: "Voice Actor (Anxiety)", imageUrl: "https://i.postimg.cc/h4kbvf24/Anupama-Parameswaran.jpg" },
            { name: "Kayadu Lohar", role: "Voice Actor (Sadness)", imageUrl: "https://i.postimg.cc/vmZ5k9Zh/kayadu-lohar.jpg" },
            { name: "V J siddhu", role: "Voice Actor (Riley)", imageUrl: "https://i.postimg.cc/KvhBFCYR/vj.jpg" },
            { name: "Harshath Khan", role: "Voice Actor (Riley)", imageUrl: "https://i.postimg.cc/YqNgS848/kan.jpg" }
        ],
        trailers: 3
    },
    {
        id: "ET00384965",
        title: "Minecraft",
        posterUrl: "https://i.postimg.cc/8cRFjPCs/minecraft.jpg",
        likes: "30.7K",
        rating: null,
        votes: null,
        ageRating: "A",
        languages: ["English", "Hindi", "Tamil", "Telugu","Malayalam"],
        genres: ["Sci-Fi", "Drama"],
        formats: ["2D", "IMAX 2D", "4DX"],
        duration: "1h 40m",
        releaseDate: "27 Jun, 2025",
        synopsis: "Welcome to the world of Minecraft, where creativity isn`t just a tool-it`s key to survival! Four misfits find themselves grappling with everyday challenges when they are suddenly pulled through a mysterious portal into the Overworld-a bizarre, cubic wonderland fueled by imagination. To return home, they must navigate this unfamiliar realm, master its mechanics, and fend off threats like Piglins and Zombies. Guided by an unexpected expert crafter, their journey will test their courage and push them to rediscover the unique creativity that will help them thrive. Not just in this world, but in their own.",
        cast: [
            { name: "Jason Momoa", role: "Actor", imageUrl: "https://i.postimg.cc/8CsDwq5Z/Jason-Momoa-mine-1.avif" },
            { name: "Emma Myers", role: "Actor", imageUrl: "https://i.postimg.cc/7P9sYbXT/Emma-Myers-mine-2.avif" },
            { name: "Jack Black", role: "Actor", imageUrl: "https://i.postimg.cc/g0p8ZH2c/Jack-Black-mine3.webp" },
            { name: "Sebastian Eugene Hansen", role: "Actor", imageUrl: "https://i.postimg.cc/4nCmTXK4/Sebastian-Eugene-Hansen-mine4.jpg" },
            { name: "Pauline Chalamet", role: "Actor", imageUrl: "https://i.postimg.cc/BQDCP6Bg/Pauline-Chalamet-mine-5.jpg" },
            { name: "Jemaine Clememt", role: "Actor", imageUrl: "https://i.postimg.cc/KY97hgmZ/Jemaine-Clememt-mine6.jpg" }
        ],
        trailers: 2
    }
];